### ISSUE TITLE
About camus dataset split?

### ISSUE THREAD

**Issue by STHxiao** [GillesVanDeVyver/GCN_multistructure#3]
Hi, thanks for your work, how is the camus dataset divided into 10 folds? I didn't find any code on the web about this part of the division? Please send it to my email `shunkai.xiao@foxmail.com` if you are willing to share it, thank you very very much!

**Comment by GillesVanDeVyver** [comment]
Hello STHxiao, you can find this information under files/subgroups_CAMUS/ in this repository

These are the same folds as used in Leclerc et al.
S. Leclerc, E. Smistad, J. Pedrosa, A. Ostvik, et al.
"Deep Learning for Segmentation using an Open Large-Scale Dataset in 2D Echocardiography" in IEEE Transactions on Medical Imaging, vol. 38, no. 9, pp. 2198-2210, Sept. 2019.

**Comment by STHxiao** [comment]
Thank you very much! There is no code related to the dataset division? I'm curious how this division is generated?

**Comment by GillesVanDeVyver** [comment]
I do not have the code that generated the division.

From Leclerc et al:
"The dataset was divided into 10 folds to perform standard
cross-validation for the machine learning methods. Each fold
contains 50 patients with the same distributions in terms of
image quality and LVEF as the full dataset"

**Comment by STHxiao** [comment]
Okay, thanks again and good luck with everything!
